function renderGroups(){
  $('#groups').innerHTML=state.groups.map(g=>`<div class="group"><div class="group-icon">${esc(g.icon)}</div><div class="group-info"><b>${esc(g.name)}</b><small>${g.members} agza · ${esc(g.description||'')}</small></div><button class="mini" data-group-toggle="${esc(g.id)}">${g.joined?'Goşuldy ✓':'Goşul'}</button>${g.owner?`<button class="mini" data-group-delete="${esc(g.id)}" aria-label="${esc(g.name)} gurnagyny aýyr">🗑️</button>`:''}</div>`).join('');
  $$('[data-group-toggle]').forEach(b=>b.onclick=()=>{const g=state.groups.find(x=>x.id===b.dataset.groupToggle);g.joined=!g.joined;g.members=Math.max(0,g.members+(g.joined?1:-1));addNotification(g.joined?`${g.name} gurnagyna goşuldyňyz`:`${g.name} gurnagyndan çykdyňyz`,'🏫','groups');save();renderGroups();toast(g.joined?'Gurnaga goşuldyňyz':'Gurnakdan çykdyňyz')});
  $$('[data-group-delete]').forEach(b=>b.onclick=()=>{if(confirm('Bu gurnagy aýyrmalymy?')){state.groups=state.groups.filter(g=>g.id!==b.dataset.groupDelete);save();renderGroups();toast('Gurnak aýryldy')}});
}
function openGroupComposer(){openModal({title:'Täze gurnak döret',confirmText:'Döret',body:`<div class="form-grid"><div class="field"><label>Gurnagyň ady</label><input id="groupName" maxlength="80"></div><div class="field"><label>Nyşan</label><input id="groupIcon" value="🏫" maxlength="4"></div><div class="field"><label>Beýany</label><textarea id="groupDescription" maxlength="300"></textarea></div></div>`,onConfirm:()=>{const name=$('#groupName').value.trim();if(!name)throw new Error('Gurnagyň adyny ýazyň.');state.groups.unshift({id:uid(),name,members:1,icon:$('#groupIcon').value.trim()||'🏫',description:$('#groupDescription').value.trim(),joined:true,owner:true});addNotification(`${name} gurnagy döredildi`,'🏫','groups');save();renderGroups();closeModal();toast('Gurnak döredildi')}});}

function currentChat(){return state.chats.find(c=>c.id===state.activeChat)||state.chats[0];}
function renderChats(){
  const q=$('#chatSearch')?.value.toLowerCase().trim()||'';const list=state.chats.filter(c=>!q||`${c.name} ${c.preview}`.toLowerCase().includes(q));
  $('#chatList').innerHTML=list.map(c=>`<button class="chat-user ${state.activeChat===c.id?'active':''}" data-chat="${esc(c.id)}"><img class="avatar" src="${esc(c.avatar)}" alt=""><span><b>${esc(c.name)}</b><small>${esc(c.preview||'')}</small></span>${c.unread?`<i class="unread-dot">${c.unread}</i>`:''}</button>`).join('')||'<div class="empty">Çat tapylmady.</div>';
  $$('[data-chat]').forEach(b=>b.onclick=()=>{state.activeChat=b.dataset.chat;const c=currentChat();c.unread=0;save();renderChats();renderMessages()}); updateBadges();
}
function renderMessages(){const c=currentChat();if(!c){$('#chatHead').textContent='Çat ýok';$('#messages').innerHTML='<div class="empty">Täze çat başlaň.</div>';return;}$('#chatHead').textContent=c.name;$('#messages').innerHTML=c.messages.map(m=>`<div class="bubble-wrap ${m.from==='me'?'me':''}"><div class="bubble">${esc(m.text)}</div><div class="bubble-time">${esc(m.time||'')}</div></div>`).join('')||'<div class="empty">Heniz habar ýok. Ilkinji habary ýazyň.</div>';$('#messages').scrollTop=$('#messages').scrollHeight;}
function openNewChat(){const available=state.people.map(p=>`<button class="choice" data-chat-choice="${esc(p.id)}"><img class="avatar" src="${esc(p.avatar)}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.city)} · ${esc(p.job)}</small></span></button>`).join('');openModal({title:'Täze çat başla',hideConfirm:true,body:`<div class="choice-list">${available}</div>`});$$('[data-chat-choice]').forEach(b=>b.onclick=()=>{closeModal();startChatWithPerson(b.dataset.chatChoice)});}

function renderMedia(){
  const filter=state.mediaFilter||'all';$$('[data-media-filter]').forEach(b=>{const active=b.dataset.mediaFilter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const list=state.media.filter(m=>filter==='all'||m.type===filter);
  $('#mediaGrid').innerHTML=list.map(m=>{const src=safeLocalUrl(m.src,{allowDataImage:m.type==='image'});if(!src)return '';return `<button class="media-item" data-media="${esc(m.id)}">${m.type==='image'?`<img src="${esc(src)}" alt="${esc(m.title)}" loading="lazy">`:isDirectVideo(src)?`<video src="${esc(src)}" muted preload="metadata"></video>`:`<div class="media-placeholder">🎥</div>`}<span class="media-label">${esc(m.title)}</span></button>`}).join('')||'<div class="empty">Bu bölümde media ýok.</div>';
  $$('[data-media]').forEach(b=>b.onclick=()=>viewMedia(b.dataset.media));
}
function viewMedia(id){const m=state.media.find(x=>x.id===id);if(!m)return;const src=safeLocalUrl(m.src,{allowDataImage:m.type==='image'});if(!src){toast('Media salgysy howpsuz däl');return}const content=m.type==='image'?`<img src="${esc(src)}" alt="${esc(m.title)}">`:isDirectVideo(src)?`<video controls autoplay src="${esc(src)}"></video>`:`<div class="story-view"><h2>${esc(m.title)}</h2><a class="primary" target="_blank" rel="noopener noreferrer" href="${esc(src)}">Wideony aç</a></div>`;openLightbox(`${content}${m.ownerId==='me'?`<button class="danger media-delete" data-delete-media="${esc(m.id)}">Aýyr</button>`:''}`);$('[data-delete-media]')?.addEventListener('click',()=>{if(confirm('Mediany aýyrmalymy?')){state.media=state.media.filter(x=>x.id!==id);save();renderMedia();closeLightbox();toast('Media aýryldy')}});}
function openMediaUpload(){openModal({title:'Media ýükle',confirmText:'Ýükle',body:`<div class="form-grid"><div class="field"><label>Görnüşi</label><select id="mediaType"><option value="image">Surat</option><option value="video">Wideo URL</option></select></div><div class="field"><label>Ady</label><input id="mediaTitle" maxlength="100"></div><div class="field" id="mediaFileField"><label>Surat faýly</label><input id="mediaFile" type="file" accept="image/*"><div class="field-help">Iň köp 1.5 MB.</div></div><div class="field"><label>Ýa-da URL</label><input id="mediaUrl" type="url" placeholder="https://..."></div></div>`,onConfirm:async()=>{const type=$('#mediaType').value;const file=$('#mediaFile')?.files[0];const src=type==='image'?(file?await fileToDataUrl(file):normalizeLocalUrl($('#mediaUrl').value.trim())):normalizeLocalUrl($('#mediaUrl').value.trim());if(!src)throw new Error('Faýl ýa-da URL giriziň.');state.media.unshift({id:uid(),type,src,title:$('#mediaTitle').value.trim()||'Täze media',ownerId:'me'});save();renderMedia();closeModal();toast('Media ýüklendi')}});$('#mediaType').onchange=e=>$('#mediaFileField').classList.toggle('hidden',e.target.value==='video');}

function renderEvents(){
  const sorted=[...state.events].sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`));
  $('#events').innerHTML=sorted.map(e=>{const d=formatEventDate(e.date);const past=new Date(`${e.date}T${e.time||'00:00'}`)<new Date();return `<div class="event ${past?'past':''}"><div class="datebox"><small>${esc(d.month)}</small><b>${esc(d.day)}</b></div><div><b>${esc(e.title)}</b><p>${esc(e.location)} · ${esc(e.time)}</p><small>${esc(e.description||'')}</small></div><div class="event-actions"><button class="secondary" data-attend="${esc(e.id)}">${e.attending?'Gatnaşaryn ✓':'Gatnaşaryn'}</button>${e.ownerId==='me'?`<button class="mini" data-delete-event="${esc(e.id)}" aria-label="${esc(e.title)} çäresini aýyr">🗑️</button>`:''}</div></div>`}).join('')||'<div class="empty">Heniz çäre ýok.</div>';
  $$('[data-attend]').forEach(b=>b.onclick=()=>{const e=state.events.find(x=>x.id===b.dataset.attend);e.attending=!e.attending;addNotification(e.attending?`${e.title} çäresine gatnaşygyňyz tassyklandy`:`${e.title} çäresine gatnaşygyňyz ýatyryldy`,'📅','events');save();renderEvents();renderNextEvent();toast(e.attending?'Gatnaşyk tassyklandy':'Gatnaşyk ýatyryldy')});
  $$('[data-delete-event]').forEach(b=>b.onclick=()=>{if(confirm('Çäräni aýyrmalymy?')){state.events=state.events.filter(e=>e.id!==b.dataset.deleteEvent);save();renderEvents();renderNextEvent();toast('Çäre aýryldy')}});
}
function openEventComposer(){const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);openModal({title:'Täze çäre döret',confirmText:'Döret',body:`<div class="form-grid"><div class="field"><label>Çäräniň ady</label><input id="eventTitle" maxlength="120"></div><div class="form-grid two"><div class="field"><label>Sene</label><input id="eventDate" type="date" min="${new Date().toISOString().slice(0,10)}" value="${tomorrow}"></div><div class="field"><label>Wagt</label><input id="eventTime" type="time" value="18:00"></div></div><div class="field"><label>Ýer</label><input id="eventLocation" maxlength="180"></div><div class="field"><label>Beýany</label><textarea id="eventDescription" maxlength="500"></textarea></div></div>`,onConfirm:()=>{const title=$('#eventTitle').value.trim(),date=$('#eventDate').value,time=$('#eventTime').value,location=$('#eventLocation').value.trim();if(!title||!date||!time||!location)throw new Error('Ady, senesi, wagty we ýeri hökmany.');state.events.push({id:uid(),title,date,time,location,description:$('#eventDescription').value.trim(),attending:true,ownerId:'me'});addNotification(`${title} çäresi döredildi`,'📅','events');save();renderEvents();renderNextEvent();closeModal();toast('Çäre döredildi')}});}
function renderNextEvent(){const future=[...state.events].filter(e=>new Date(`${e.date}T${e.time}`)>=new Date()).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`))[0];$('#nextEvent').innerHTML=future?`<div class="next-event-card"><b>${esc(future.title)}</b><small>${esc(future.date)} · ${esc(future.time)}</small><small>${esc(future.location)}</small></div>`:'<div class="empty">Ýakyn çäre ýok.</div>';}

function renderNotifications(){const unread=state.notifications.filter(n=>!n.read).length;$('#noticeBadge').textContent=unread;$('#noticeBadge').classList.toggle('hidden',!unread);$('#notifications').innerHTML=state.notifications.map(n=>`<button class="notice ${n.read?'':'unread'}" data-notice="${esc(n.id)}"><span>${esc(n.icon)}</span><span><b>${esc(n.text)}</b><small>${esc(n.time)}</small></span></button>`).join('')||'<div class="empty">Bildiriş ýok.</div>';$$('[data-notice]').forEach(b=>b.onclick=()=>{const n=state.notifications.find(x=>x.id===b.dataset.notice);n.read=true;save();renderNotifications();if(n.page)showPage(n.page)});}

function renderProfile(){const u=state.currentUser;$('#profileAvatar').src=u.avatar;$('#profileName').textContent=u.name;$('#profileBio').textContent=u.bio;$('#profileMeta').textContent=`${u.city} · ${u.role}`;$('#notifySwitch').classList.toggle('on',state.notify);$('#notifySwitch').setAttribute('aria-checked',String(state.notify));state.privacy='school';$('#privacy').value='school';}
function openProfileEditor(){const u=state.currentUser;openModal({title:'Profili üýtget',confirmText:'Sakla',body:`<div class="form-grid"><div class="field"><label>Doly ady</label><input id="profileNameInput" value="${esc(u.name)}" maxlength="100"></div><div class="field"><label>Gysga ady</label><input id="profileShortInput" value="${esc(u.shortName||'')}" maxlength="30"></div><div class="form-grid two"><div class="field"><label>Şäher</label><input id="profileCityInput" value="${esc(u.city)}" maxlength="80"></div><div class="field"><label>Rol / iş</label><input id="profileRoleInput" value="${esc(u.role)}" maxlength="80"></div></div><div class="field"><label>Bio</label><textarea id="profileBioInput" maxlength="500">${esc(u.bio)}</textarea></div><div class="field"><label>Avatar URL-si</label><input id="profileAvatarInput" value="${esc(u.avatar)}" type="url"></div><div class="field"><label>Ýa-da avatar faýly</label><input id="profileAvatarFile" type="file" accept="image/*"><div class="field-help">Iň köp 1.5 MB.</div></div></div>`,onConfirm:async()=>{const name=$('#profileNameInput').value.trim();if(!name)throw new Error('Adyňyzy ýazyň.');const file=$('#profileAvatarFile').files[0];const avatar=file?await fileToDataUrl(file):normalizeLocalUrl($('#profileAvatarInput').value.trim()||u.avatar,{allowDataImage:true});state.currentUser={...u,name,shortName:$('#profileShortInput').value.trim()||name.split(' ')[0],city:$('#profileCityInput').value.trim(),role:$('#profileRoleInput').value.trim(),bio:$('#profileBioInput').value.trim(),avatar};state.posts.forEach(p=>{if(p.ownerId==='me'){p.author=name;p.role=state.currentUser.role;p.avatar=avatar}});save();updateUserUI();renderProfile();renderAllPosts();renderStories();closeModal();toast('Profil saklandy')}});}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`klas-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Ätiýaç nusga taýýarlandy');}
async function importData(file){if(!file)return;try{const data=JSON.parse(await file.text());state=normalizeState(data);save();renderEverything();toast('Maglumatlar üstünlikli dikeldildi')}catch{toast('JSON faýly nädogry ýa-da zaýalanan')}}

function globalSearch(q){
  q=q.toLowerCase().trim();const box=$('#searchResults'),input=$('#searchInput');$('#searchClear').classList.toggle('hidden',!q);if(q.length<2){box.classList.add('hidden');box.innerHTML='';input.setAttribute('aria-expanded','false');return;}
  const groups=[];
  const people=state.people.filter(p=>`${p.name} ${p.city} ${p.job}`.toLowerCase().includes(q)).slice(0,5);
  const g=state.groups.filter(x=>`${x.name} ${x.description}`.toLowerCase().includes(q)).slice(0,5);
  const posts=state.posts.filter(p=>`${p.author} ${p.text}`.toLowerCase().includes(q)).slice(0,5);
  const events=state.events.filter(e=>`${e.title} ${e.location} ${e.description}`.toLowerCase().includes(q)).slice(0,5);
  if(people.length)groups.push(`<div class="search-group-title">Synpdaşlar</div>${people.map(p=>`<button class="search-result" data-search-person="${esc(p.id)}"><img class="avatar" src="${esc(p.avatar)}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.city)} · ${esc(p.job)}</small></span></button>`).join('')}`);
  if(g.length)groups.push(`<div class="search-group-title">Gurnaklar</div>${g.map(x=>`<button class="search-result" data-search-page="groups"><span>🏫</span><span><b>${esc(x.name)}</b><small>${esc(x.description)}</small></span></button>`).join('')}`);
  if(posts.length)groups.push(`<div class="search-group-title">Postlar</div>${posts.map(p=>`<button class="search-result" data-search-post="${esc(p.id)}"><span>📝</span><span><b>${esc(p.author)}</b><small>${esc(p.text.slice(0,100))}</small></span></button>`).join('')}`);
  if(events.length)groups.push(`<div class="search-group-title">Çäreler</div>${events.map(e=>`<button class="search-result" data-search-page="events"><span>📅</span><span><b>${esc(e.title)}</b><small>${esc(e.date)} · ${esc(e.location)}</small></span></button>`).join('')}`);
  box.innerHTML=groups.join('')||'<div class="empty">Netije tapylmady.</div>';box.classList.remove('hidden');input.setAttribute('aria-expanded','true');
  $$('[data-search-person]',box).forEach(b=>b.onclick=()=>{startChatWithPerson(b.dataset.searchPerson);box.classList.add('hidden');input.setAttribute('aria-expanded','false')});
  $$('[data-search-page]',box).forEach(b=>b.onclick=()=>{showPage(b.dataset.searchPage);box.classList.add('hidden');input.setAttribute('aria-expanded','false')});
  $$('[data-search-post]',box).forEach(b=>b.onclick=()=>{showPage('feed');box.classList.add('hidden');input.setAttribute('aria-expanded','false');setTimeout(()=>$(`[data-post-card="${CSS.escape(b.dataset.searchPost)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)});
}
