const K='klas-v3-state';
const defaults={dark:false,notify:true,privacy:'classmates',attending:false,activeChat:0,posts:[
{id:1,author:'Maksat Dowletow',role:'Administrator',avatar:'https://i.pravatar.cc/100?img=12',time:'12 minut öň',text:'Klas platformasynyň täze görnüşine hoş geldiňiz! Bu giňişlikde synpdaşlar bilen habarlaşyp, ýatlamalary paýlaşyp we duşuşyklary meýilleşdirip bilersiňiz.',image:'https://picsum.photos/seed/school2000/1000/600',likes:36,comments:8,liked:false,saved:false},
{id:2,author:'Aýlar Rejepowa',role:'2000-nji ýyl uçurymy',avatar:'https://i.pravatar.cc/100?img=47',time:'1 sagat öň',text:'Köne synp suratlaryny täze alboma goşdum. Hemmeleri bellik etmäge kömek ediň!',image:'https://picsum.photos/seed/classmemory/1000/600',likes:24,comments:12,liked:true,saved:true}],
people:[['Aýlar Rejepowa','Aşgabat · Mugallym',47],['Serdar Ataýew','Kerki · Inžener',11],['Mähri Orazowa','Türkmenabat · Lukman',44],['Döwlet Myradow','Aşgabat · Telekeçi',15]],
groups:[['Öde Abdullaýew mekdebi','428 agza','🏫'],['2000-nji ýyl uçurymlary','128 agza','🎓'],['Futbol gurnagy','74 agza','⚽'],['Edebiýat söýüjiler','52 agza','📚']],
chats:[{name:'Aýlar Rejepowa',avatar:47,preview:'Suratlary gördüňmi?',messages:[['them','Salam! Täze albomy gördüňmi?'],['me','Hawa, örän gowy suratlar eken.']]},{name:'2000 uçurymlar',avatar:11,preview:'Duşuşygy tassyklaýarys',messages:[['them','15-nji awgust üçin duşuşygy tassyklaýarys.'],['me','Men gatnaşaryn.']]},{name:'Serdar Ataýew',avatar:15,preview:'Soňky habar',messages:[['them','Soňky täzelikleri gördüňmi?']]}],
notifications:[{id:1,icon:'💬',text:'Aýlar size täze habar iberdi',time:'5 minut öň',read:false},{id:2,icon:'👥',text:'Serdar synpdaşlyk haýyşyňyzy kabul etdi',time:'24 minut öň',read:false},{id:3,icon:'📅',text:'Duşuşyk senesi täzelendi',time:'1 sagat öň',read:false}]};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem(K)||'{}')}}catch{state=structuredClone(defaults)}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],save=()=>localStorage.setItem(K,JSON.stringify(state));
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2100)}
function showPage(n){$$('.page').forEach(x=>x.classList.remove('active'));$('#page-'+n)?.classList.add('active');$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===n));$('#sidebar').classList.remove('open');if(n==='saved')renderSaved();if(n==='notifications')renderNotifications();scrollTo({top:0,behavior:'smooth'})}
$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function avatar(i){return `https://i.pravatar.cc/100?img=${i}`}
function postHTML(p){return `<article class="card post"><div class="post-head"><img class="avatar" src="${p.avatar}" alt="${esc(p.author)}"><div class="post-meta"><b>${esc(p.author)}</b><small>${esc(p.role)} · ${esc(p.time)}</small></div><button class="post-menu" data-save="${p.id}" title="Sakla">${p.saved?'🔖':'⋯'}</button></div><div class="post-text">${esc(p.text)}</div>${p.image?`<img class="post-image" src="${p.image}" alt="Post suraty">`:''}<div class="post-stats"><span>👍 ${p.likes}</span><span>${p.comments} teswir</span></div><div class="post-actions"><button data-like="${p.id}" class="${p.liked?'on':''}">👍 Hala</button><button data-comment="${p.id}">💬 Teswir</button><button data-share="${p.id}">↗ Paýlaş</button></div></article>`}
function bindPosts(){$$('[data-like]').forEach(b=>b.onclick=()=>{const p=state.posts.find(x=>x.id==b.dataset.like);p.liked=!p.liked;p.likes+=p.liked?1:-1;save();renderFeed();renderSaved()});$$('[data-save]').forEach(b=>b.onclick=()=>{const p=state.posts.find(x=>x.id==b.dataset.save);p.saved=!p.saved;save();renderFeed();renderSaved();toast(p.saved?'Post saklandy':'Saklananlardan aýryldy')});$$('[data-comment]').forEach(b=>b.onclick=()=>{const t=prompt('Teswiriňizi ýazyň:');if(!t?.trim())return;state.posts.find(x=>x.id==b.dataset.comment).comments++;save();renderFeed();toast('Teswir goşuldy')});$$('[data-share]').forEach(b=>b.onclick=async()=>{const p=state.posts.find(x=>x.id==b.dataset.share);try{await navigator.clipboard.writeText(`${p.author}: ${p.text}`);toast('Post nusgalandy')}catch{toast('Paýlaşmak taýýar')}})}
function renderFeed(){$('#feed').innerHTML=state.posts.map(postHTML).join('');bindPosts()}
function renderSaved(){const p=state.posts.filter(x=>x.saved);$('#saved').innerHTML=p.length?p.map(postHTML).join(''):'<div class="notice">Heniz saklanan post ýok.</div>';bindPosts()}
function renderPeople(){$('#people').innerHTML=state.people.map(p=>`<div class="person"><img class="avatar" src="${avatar(p[2])}" alt="${p[0]}"><div class="person-info"><b>${p[0]}</b><small>${p[1]}</small></div><button class="mini add-person">Goş</button></div>`).join('');$$('.add-person').forEach(b=>b.onclick=()=>{b.textContent='Ugradyldy';b.disabled=true;toast('Synpdaşlyk haýyşy ugradyldy')})}
function renderGroups(){$('#groups').innerHTML=state.groups.map(g=>`<div class="group"><div class="group-icon">${g[2]}</div><div class="group-info"><b>${g[0]}</b><small>${g[1]}</small></div><button class="mini join-group">Goşul</button></div>`).join('');$$('.join-group').forEach(b=>b.onclick=()=>{b.textContent='Goşuldy';toast('Gurnaga goşuldyňyz')})}
function renderSuggestions(){$('#suggestions').innerHTML=state.people.slice(0,3).map(p=>`<div class="suggestion"><img class="avatar" src="${avatar(p[2])}" alt=""><div><b>${p[0]}</b><small>${p[1].split(' · ')[0]}</small></div><button class="mini">＋</button></div>`).join('')}
function renderChats(){$('#chatList').innerHTML=state.chats.map((c,i)=>`<button class="chat-user ${state.activeChat===i?'active':''}" data-chat="${i}"><img class="avatar" src="${avatar(c.avatar)}" alt=""><span><b>${c.name}</b><small>${esc(c.preview)}</small></span></button>`).join('');$$('[data-chat]').forEach(b=>b.onclick=()=>{state.activeChat=+b.dataset.chat;save();renderChats();renderMessages()})}
function renderMessages(){const c=state.chats[state.activeChat];$('#chatHead').textContent=c.name;$('#messages').innerHTML=c.messages.map(m=>`<div class="bubble ${m[0]==='me'?'me':''}">${esc(m[1])}</div>`).join('');$('#messages').scrollTop=$('#messages').scrollHeight}
function renderNotifications(){const unread=state.notifications.filter(n=>!n.read).length;$('#noticeBadge').textContent=unread;$('#noticeBadge').style.display=unread?'grid':'none';$('#notifications').innerHTML=state.notifications.map(n=>`<button class="notice ${n.read?'':'unread'}" data-notice="${n.id}"><span>${n.icon}</span><span><b>${esc(n.text)}</b><small>${n.time}</small></span></button>`).join('');$$('[data-notice]').forEach(b=>b.onclick=()=>{state.notifications.find(n=>n.id==b.dataset.notice).read=true;save();renderNotifications()})}
function applyTheme(){document.body.classList.toggle('dark',state.dark);$('#themeBtn').textContent=state.dark?'☀️':'🌙';$('#darkSwitch').classList.toggle('on',state.dark)}
$('#themeBtn').onclick=()=>{state.dark=!state.dark;save();applyTheme()};$('#darkSwitch').onclick=()=>$('#themeBtn').click();$('#notifySwitch').classList.toggle('on',state.notify);$('#notifySwitch').onclick=()=>{state.notify=!state.notify;$('#notifySwitch').classList.toggle('on',state.notify);save();toast('Sazlama saklandy')};$('#privacy').value=state.privacy;$('#privacy').onchange=e=>{state.privacy=e.target.value;save();toast('Gizlinlik sazlamasy saklandy')};
$('#composerOpen').onclick=()=>{$('#composerModal').classList.add('open');$('#postText').focus()};function closeComposer(){$('#composerModal').classList.remove('open')}$('#composerClose').onclick=closeComposer;$('#composerCancel').onclick=closeComposer;$('#composerModal').onclick=e=>{if(e.target===$('#composerModal'))closeComposer()};$('#publishBtn').onclick=()=>{const t=$('#postText').value.trim();if(!t)return toast('Post üçin tekst ýazyň');state.posts.unshift({id:Date.now(),author:'Maksat Dowletow',role:'Administrator',avatar:avatar(12),time:'häzir',text:t,likes:0,comments:0,liked:false,saved:false});$('#postText').value='';closeComposer();save();renderFeed();toast('Post çap edildi')};
$('#chatForm').onsubmit=e=>{e.preventDefault();const i=$('#chatInput'),t=i.value.trim();if(!t)return;state.chats[state.activeChat].messages.push(['me',t]);state.chats[state.activeChat].preview=t;i.value='';save();renderChats();renderMessages()};
$('#readAll').onclick=()=>{state.notifications.forEach(n=>n.read=true);save();renderNotifications();toast('Ähli bildirişler okalan edildi')};$('#attendBtn').textContent=state.attending?'Gatnaşaryn ✓':'Gatnaşaryn';$('#attendBtn').onclick=()=>{state.attending=!state.attending;$('#attendBtn').textContent=state.attending?'Gatnaşaryn ✓':'Gatnaşaryn';save();toast(state.attending?'Gatnaşyk tassyklandy':'Gatnaşyk ýatyryldy')};$('#inviteBtn').onclick=()=>toast('Çakylyk baglanyşygy taýýarlandy');
$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase().trim();if(q.length<2)return;const hay=[...state.people.map(x=>x[0]),...state.groups.map(x=>x[0]),...state.posts.map(x=>x.text)].filter(x=>x.toLowerCase().includes(q));toast(hay.length?`${hay.length} netije tapyldy`:'Netije tapylmady')};
renderFeed();renderSaved();renderPeople();renderGroups();renderSuggestions();renderChats();renderMessages();renderNotifications();applyTheme();